### ISSUE TITLE
response none and no records appearing

### ISSUE THREAD

**Issue by ZalgirisKaunas** [its-tas/stripe-php-webhook#1]
I have enabled db logging and set debug to 1 but when I fire event from my stripe dashboard it says:
Test webhook sent successfully
Response
None

and the records are not created in the DB neither in log file

**Comment by jgregmccormick** [comment]
I am seeing the same thing, was there a fix?

**Comment by 140toesandfingers** [comment]
I have the same thing happening with me.  Found out that evt_00000000000000 was coming back.  How?
 $event_json = json_decode($input);		
file_put_contents('webhooklogs.txt', print_r($event_json, true));//Daron added this code to see what is going on

The issue here is that the event you are trying to retrieve through the API evt_00000000000000 doesn't exist in your account which is why it fails.

When you use the "Send test webhook..." button in the dashboard it simply sends a generic event with fake data in it. All the identifiers would have 0 into it so there is no way to retrieve it through the Retrieve Event API.

What you need to do here instead is use real events in your account. To do that, you can simply create a customer or a charge in the dashboard in Test mode which would automatically send the event customer.created or charge.created to your webhook endpoint and the code should then work as expected.
